version: 2
jobs:
  build:
    docker:
      - image: marcrowo/shield-study-utils-base:3
        environment:
          DISPLAY: :10

    working_directory: /shield-study-addon-utils

    steps:
      - run:
          name: xvfb and openbox
          command: Xvfb $DISPLAY -ac & sleep 3 & openbox
          background: true

      - checkout

      - run: npm install

      - run:
          name: build study apis (webpack) and lint
          command: npm run build

      - run:
          name: build study apis (webpack) and lint + build test add-on
          command: npm run test-addon:build

      - run:
          name: build study apis (webpack) and lint + build test add-on + functional tests
          command: npm run test

      - store_artifacts:
          path: "examples/test-addon/dist/shield_utils_test_add-on-1.0.0.zip"
