# Interface schema
# https://firefox-source-docs.mozilla.org/toolkit/components/extensions/webextensions/schema.html
# possible types are here
# - https://searchfox.org/mozilla-central/source/toolkit/components/extensions/Schemas.jsm#2418-2426
#
# - properties
# - functions
# - events
# - types
#
# - type property:
#   boolean, integer, number, string, array, object, or any.
#

# TODO
# - add json schema types
# - do we want to expose any of the sampling / hashing stuff?
# - mention / decide how to handle all
---
- namespace: study
  description: Interface for shield studies, for use by `background.js` scripts.
  apiVersion: 5  # for dev use
  types:
  - name: studySetup
  - name: weightedVariations
  - name: anEnding
  - name: telemetrySelectionOptions

  functions:

  ## study lifecycle
  - name: configure
    type: function
    description: Configure the study.  Most things can't work without this
    async: true
    fakereturn:
    parameters:
    - name: studySetup
      type: object
      # with a variation included.
      # expiration?  -- TODO No, this should be with usual webExt timers.

  - name: install
    async: true
    description: all for side effects (sending 'install', 'enter') pings
    returns:  Nothing
    parameters: []

  - name: startup
    async: true
    description: all for side effects (setActiveExperiment)
    returns:  Nothing
    parameters: []

  - name: endStudy
    async: true
    defaultReturn: "endingName"
    description: Optionally opens url, then ends study with pings ending, exit.  Study can only have one ending.  Uninstalls addon?
    parameters:
    - name: anEnding
      type: object
    # should be anEnding Object
    returns: none


  ## study information things
  - name: info
    async: true
    defaultReturn: {variation: "styleA"}
    returns: object with branch and other useful data from a configured study

  - name: permissions
    async: true
    defaultReturn: {shield: true, pioneer: false}
    returns: object of permissions with keys shield, pioneer, telemetry, 'ok'

  # telemetry related things
  - name: sendTelemetry
    async: true
    parameters:
    - name: payload
      type: object  # TODO copy existing?
    - name: type
    defaultReturn: undefined  # exception if out of policy based on config
    returns:  Nothing

  - name: getTelemetry
    async: true
    defaultReturn: [{pingType: 'main'}]
    returns:  Array of Telemetry pings
    parameters:
    - name: telemetrySelectionOptions
      description: `{ type, n, minTimestamp, headersOnly }`

  # utilities
  - name: deterministicVariation
    defaultReturn: "styleA"
    returns: Name of a variation from weightedVariations
    async: true
    parameters:
    - name: weightedVariations
      type: object
    - name: algorithm
      type: string
    - name: fraction
      optional: true
      type: Number

  - name: surveyUrl
    async: true
    defaultReturn: 'https://example.com?version=59.0&branch=studyA'
    parameters:
    - name: baseUrl
      type: string
    returns: a url with queryArgs appended / mixed using our usual pattern

  - name: validateJSON
    async: true
    defaultReturn: {valid: true, errors: []}
    returns: a validation object
    parameters:
    - name: anObject
      type: object
    - name: schema
      type: object  # a jsonschema

  # things that would be 'listeners' are 'events' in webExtensions
  # https://github.com/motin/shield-studies-addon-template/blob/convert-to-webextension-experiments/src/privileged/introductionNotificationBar/api.js#L107
  # https://github.com/motin/shield-studies-addon-template/blob/convert-to-webextension-experiments/src/privileged/introductionNotificationBar/schema.json#L15

  # https://firefox-source-docs.mozilla.org/toolkit/components/extensions/webextensions/background.html#javascript-apis
  # https://firefox-source-docs.mozilla.org/toolkit/components/extensions/webextensions/events.html
  # https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/parent/ext-runtime.js#41
  # https://searchfox.org/mozilla-central/source/toolkit/components/extensions/ExtensionCommon.jsm#1671
  events:
  - name: onPermissionsChange
    type: function
    defaultReturn: {shield: true, pioneer: false}
    description: Fires whenever any 'permission' changes, with the new permissions object
    parameters:  # for the callback
    - name: updatedPermissions
      type: object

