# Interface schema
# https://firefox-source-docs.mozilla.org/toolkit/components/extensions/webextensions/schema.html
# possible types are here
# - https://searchfox.org/mozilla-central/source/toolkit/components/extensions/Schemas.jsm#2418-2426
#
# - properties
# - functions
# - events
# - types
#
# - type property:
#   boolean, integer, number, string, array, object, or any.
#

# TODO
# - add json schema types
# - do we want to expose any of the sampling / hashing stuff?
# - mention / decide how to handle all
---
- namespace: study
  description: Interface for shield studies, for use by `background.js` scripts.
  apiVersion: 5  # for dev use
  types:   # TODO @glind to actually get this back out of the schemas.json
  - name: studySetup
  - name: weightedVariations
  - name: anEnding
  - name: telemetrySelectionOptions

  functions:

  ## study lifecycle
  - name: setup
    type: function
    description: |
      Configure the study.

      - Validate the study configuation, so that all fields needed for study lifecycle telemetry are present.
    async: true
    parameters:
    - name: studySetup
      type: object
      # with a variation included.
      # expiration?  -- TODO No, this should be with usual webExt timers.

  - name: install
    async: true
    description: all for side effects (sending 'install', 'enter') pings
    returns:  Nothing
    parameters: []

  - name: startup
    async: true
    description: all for side effects (setActiveExperiment)
    returns:  Nothing
    parameters: []

  - name: endStudy
    async: true
    defaultReturn: "endingName"
    description: Optionally opens url, then ends study with pings ending, exit.  Study can only have one ending.  Uninstalls addon?
    parameters:
    - name: anEnding
      type: object
    # should be anEnding Object
    returns: none


  ## study information things
  - name: info
    description: current study configuration, including set variation, activeExperimentName
    async: true
    defaultReturn: {variation: "styleA"}

  - name: dataPermissions
    description: object of current dataPermissions with keys shield, pioneer, telemetry, 'ok'
    async: true
    defaultReturn: {shield: true, pioneer: false}

  # telemetry related things
  - name: sendTelemetry
    async: true
    parameters:
    - name: payload
      type: object  # TODO copy existing?
    - name: type
    defaultReturn: undefined  # exception if out of policy based on config
    returns:  Nothing

  - name: getTelemetry
    async: true
    description:  for isEligible, testing, and other uses, get recent stored Telemetry pings
    defaultReturn: [{pingType: 'main'}]
    returns:  Array of Telemetry pings
    parameters:
    - name: telemetrySelectionOptions
      description: `{ type, n, minTimestamp, headersOnly }`

  # utilities
  - name: deterministicVariation
    defaultReturn: "styleA"
    returns: Name of a variation from weightedVariations
    async: true
    parameters:
    - name: weightedVariations
      type: object
    - name: algorithm
      type: string
    - name: fraction
      optional: true
      type: Number

  - name: surveyUrl
    async: true
    description : |
      Format url with study covariate queryArgs appended / mixed in.

      Use this for constructing midpoint surveys.

    defaultReturn: 'https://example.com?version=59.0&branch=studyA'
    parameters:
    - name: baseUrl
      type: string

  - name: validateJSON
    async: true
    defaultReturn: {valid: true, errors: []}
    description:  Using AJV, do jsonschema validation of an object.  Can be used to validate your arguments, packets at client.
    returns: a validation object - { bool valid, array errors }
    parameters:
    - name: someJson
      type: object
    - name: jsonschema
      descripton: a valid jsonschema object
      type: object  # a jsonschema

  # things that would be 'listeners' are 'events' in webExtensions
  # https://github.com/motin/shield-studies-addon-template/blob/convert-to-webextension-experiments/src/privileged/introductionNotificationBar/api.js#L107
  # https://github.com/motin/shield-studies-addon-template/blob/convert-to-webextension-experiments/src/privileged/introductionNotificationBar/schema.json#L15

  # https://firefox-source-docs.mozilla.org/toolkit/components/extensions/webextensions/background.html#javascript-apis
  # https://firefox-source-docs.mozilla.org/toolkit/components/extensions/webextensions/events.html
  # https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/parent/ext-runtime.js#41
  # https://searchfox.org/mozilla-central/source/toolkit/components/extensions/ExtensionCommon.jsm#1671
  events:
  - name: onDataPermissionsChange
    type: function
    defaultReturn: {shield: true, pioneer: false}
    description: Fires whenever any 'dataPermission' changes, with the new dataPermission object.  Allows watching for shield or pioneer revocation.
    parameters:  # for the callback
    - name: updatedPermissions
      type: object

